nameOverride: backend

replicaCount: 1

image:
  repository: aashihabi/task-backend
  tag: "de917fb2511149181ec5471060b5d9dc71f56fda"
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80
livenessProbe:
  enabled: true
  path: /health

readinessProbe:
  enabled: true
  path: /ready
  
resources:
  requests:
    cpu: "100m" 
    memory: "128Mi"   

  limits:
    cpu: "500m"
    memory: "512Mi"  