nameOverride: frontend

replicaCount: 1

image:
  repository: aashihabi/task-frontend
  tag: "5e31420896ae0b0f792bf65d0e3f0657fbf8f246"
  pullPolicy: IfNotPresent

containerPort: 80
ingress:
  enabled: true

service:
  type: LoadBalancer
  port: 80

livenessProbe:
  enabled: false
  path: /

resources:
  requests:
    cpu: "50m" 
    memory: "64Mi"
limits:
  cpu: "250m"    
  memory: "250Mi"
