name: CI CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-backend:${{ github.sha }} ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task-backend:${{ github.sha }}

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-frontend:${{ github.sha }} ./frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task-frontend:${{ github.sha }}

      - name: Update Helm image tags
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" helm/task-manager/values.yaml

      - name: Commit and push Helm changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/task-manager/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main